---
include:
  - project: infrastructure/gitlab-ci-helper
    file: /templates/julia.yml
  - project: infrastructure/gitlab-ci-helper
    file: /templates/common-functions.yml

.setup: &setup
  |
  echo "$common_functions" > common && source common

variables:
  # Only include Linux 64-bit jobs in the job matrix
  os: "linux"
  platform: "64-bit"
  # Exclude Documentation job from teardown stage because package does not have docs
  exclude: "\"Documentation\""

test_util_diff:
  stage: test
  before_script:
    - *setup
    - package_install jq
  script:
    # PDMats.jl has changed the structure of their codebase and the testing utilities which
    # we were using have now moved into the testing directory. We have copied the testutils
    # file into this repository to continue using it. This CI job ensures that we are aware
    # of any changes made to the file, for more information see the link:
    # https://gitlab.invenia.ca/invenia/PSDMats.jl/-/merge_requests/8#note_150819
    - 'latest=$(curl -s https://api.github.com/repos/JuliaStats/PDMats.jl/releases/latest | jq -r .tag_name)'
    - 'curl -LO https://raw.githubusercontent.com/JuliaStats/PDMats.jl/$latest/test/testutils.jl'
    - 'diff testutils.jl <(tail -n +2 test/testutils.jl) || exit 1'
  after_script:
    - '[ -f testutils.jl ] && rm testutils.jl'
