---
include:
  - project: infrastructure/gitlab-ci-helper
    file: /templates/julia.yml

variables:
  # Only include Linux 64-bit jobs in the job matrix
  os: "linux"
  platform: "64-bit"
  # Exclude Documentation job from teardown stage because package does not have docs
  exclude: "\"Documentation\""
